from app.api import auth
from app.api import user
from app.api import property
from app.api import room
from app.api import city
from app.api import property_type
from app.api import booking
from app.api import statistics
from app.api import predict
